package com.qbits.stories.anthropic;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import com.anthropic.client.AnthropicClient;
import com.anthropic.client.okhttp.AnthropicOkHttpClient;
import com.qbits.stories.DedupeProperties;
import com.qbits.stories.StoryWriterProperties;
import com.qbits.stories.domain.GroupCandidate;
import com.qbits.stories.domain.Section;
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.Test;

/**
 * Opt-in live check of the grouping prompt (spec 008 R1.2). Excluded from the normal build. Run:
 *
 * <pre>
 * ANTHROPIC_API_KEY=... QBITS_STORY_MODEL=... mvn -f backend/pom.xml verify -Plive \
 *   -Dit.test=StoryGrouperLiveIT
 * </pre>
 */
class StoryGrouperLiveIT {

  private static final Instant T = Instant.parse("2026-10-05T15:00:00Z");

  private static GroupCandidate c(
      int n, String source, int hours, String headline, String summary) {
    return new GroupCandidate(
        new UUID(0, n),
        headline,
        summary,
        Section.GLOBAL_AI_TECH,
        source,
        source,
        false,
        T.plusSeconds(3600L * hours),
        false);
  }

  @Test
  void groupsTheWatermarkTrioAndNotRelatedPolitics() { // 008 R1.2
    String key = System.getenv("ANTHROPIC_API_KEY");
    String model = System.getenv("QBITS_STORY_MODEL");
    assumeTrue(
        key != null && !key.isBlank() && model != null && !model.isBlank(),
        "set ANTHROPIC_API_KEY and QBITS_STORY_MODEL to run");
    StoryWriterProperties writer =
        new StoryWriterProperties(
            StoryWriterProperties.Mode.DIGEST,
            "anthropic",
            model,
            "v3",
            800,
            500,
            4,
            20,
            Duration.ofSeconds(30),
            Duration.ofMinutes(2),
            Duration.ofMinutes(30));
    List<GroupCandidate> candidates =
        List.of(
            c(
                1,
                "OpenAI",
                0,
                "OpenAI explains its plan for EU text watermarking rules",
                "OpenAI has outlined how it plans to follow European Union rules on text"
                    + " provenance by adding an invisible watermark to text from ChatGPT."),
            c(
                2,
                "The Verge",
                3,
                "OpenAI Rolls Out Invisible Text Watermarks in ChatGPT, Codex",
                "OpenAI is adding an invisible, machine-readable watermark to text generated by"
                    + " ChatGPT and Codex, starting with users in the European Union."),
            c(
                3,
                "TechCrunch",
                5,
                "OpenAI to watermark ChatGPT text for EU users",
                "OpenAI says it will add invisible watermarks to text generated by ChatGPT and"
                    + " Codex in the European Union to meet new rules."),
            c(
                4,
                "OpenAI",
                1,
                "OpenAI launches a cheaper voice model for developers",
                "OpenAI released a new speech model through its API at a lower price than its"
                    + " earlier voice model."),
            c(
                5,
                "TechCrunch",
                6,
                "Critics say AI text watermarks are easy to remove",
                "Researchers argue that invisible watermarks in AI-written text can be stripped"
                    + " by paraphrasing, questioning how useful the new EU rules will be."),
            // 2026-10-06 clean-up: v1 merged these related but separate Trump AI stories.
            c(
                6,
                "TechCrunch",
                0,
                "Trump Launches New Task Force on AI Safety",
                "A new government task force on AI, called the Super Intelligence Force, signals"
                    + " that AI safety remains a hot political topic."),
            c(
                7,
                "Mint",
                28,
                "Trump signs 'morally binding' pact with tech leaders on AI",
                "Trump signed a non-binding agreement with top technology executives at the White"
                    + " House and announced that AI is being renamed Super Intelligence."),
            c(
                8,
                "TechCrunch",
                5,
                "Trump Administration Tries to Rebrand AI as 'Super Intelligence'",
                "A podcast episode discusses whether the administration's super intelligence"
                    + " rebrand and safety pact can fix AI's image problem."),
            c(
                9,
                "The Guardian",
                -2,
                "Trump Picks Intelligence Chief Clayton as AI Czar",
                "Trump has put Jay Clayton, the director of national intelligence, in charge of AI"
                    + " policy at the White House."),
            c(
                10,
                "The Economic Times (ETtech)",
                11,
                "White House AI Task Force Aims to Avoid Overregulation",
                "Task force leader Jay Clayton told the Wall Street Journal the group wants to avoid"
                    + " rules so strict they slow down innovation."));

    AnthropicClient client =
        AnthropicOkHttpClient.builder().fromEnv().timeout(Duration.ofSeconds(60)).build();
    try {
      List<Set<UUID>> groups =
          new AnthropicStoryGrouper(
                  client, writer, new DedupeProperties(true, "v2", Duration.ofSeconds(60), 1000))
              .group(candidates);

      assertThat(groups).containsExactly(Set.of(new UUID(0, 1), new UUID(0, 2), new UUID(0, 3)));
    } finally {
      client.close();
    }
  }
}
